### ISSUE TITLE
Nothing happens after click on "Add TGR on BNB chain"

### ISSUE THREAD

**Issue by stuxjkee** [Hiyorimi/testing-issue-templates#3]
### Bug Type

UX

### Reproduction steps

0. Remove metamask extension
1. Go to https://tegro.money/
2. Scroll down to the footer 
3. Click on "Add TGR on BNB chain"

### Actual result

Nothing happens

### Expected result

Metamask extension page should be open

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: Windows
- Browser: Chrome
- Version 105.0.5195.125

**Comment by ferdmanlisa** [comment]
Hello dear participant! 

Please, create this issue at Tegro's repository: https://github.com/TegroTON/.github
