### ISSUE TITLE
TON DNS Auctions doesn't load

### ISSUE THREAD

**Issue by liketurbo** [Hiyorimi/testing-issue-templates#4]
### Bug Type

Functional

### Reproduction steps

1. Go to https://tonapi.io/dns/auctions

### Actual result

500 Error from server, infinite loading state

### Expected result

Show a list of auctions or message that no auctions are found

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
- OS: Windows 11
- Browser firefox
- Version 104.0.2

**Comment by Gusarich** [comment]
![image](https://user-images.githubusercontent.com/42098239/190676244-0855ae51-68e8-4401-b172-91e45ca2254f.png)
it doesn't load for me too
